import 'package:food_dictionary/model/ingredient.dart';

final allIngredietnts = <Ingredient>[
  Ingredient(
    id: 1,
    name: 'Lemon',
    per: '1 lemon (58g)',
    urlImage:
    'assets/images/search01/ingredients/1.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 2,
    name: 'Strawberry',
    cate: 'Fruit',
    per: '1 cup (152g)',
    urlImage:
    'assets/images/search01/ingredients/2.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 3,
    name: 'Grape',
    cate: 'Fruit',
    per: '1 cup (92g)',
    urlImage:
    'assets/images/search01/ingredients/3.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 4,
    name: 'Mango',
    cate: 'Fruit',
    per: '1 mango (58g)',
    urlImage:
    'assets/images/search01/ingredients/4.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 5,
    name: 'Banana',
    cate: 'Fruit',
    per: '1 medium banana (118 g)',
    urlImage:
    'assets/images/search01/ingredients/5.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 6,
    name: 'Coconut',
    cate: 'Fruit',
    per: '1 piece (45g)',
    urlImage:
    'assets/images/search01/ingredients/6.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 7,
    name: 'Chocolate',
    cate: 'Others',
    per: '1  1.4 ounce bar (41g)',
    urlImage:
    'assets/images/search01/ingredients/7.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 8,
    name: 'Honey',
    cate: 'Others',
    per: '1 tablespoon of coffee flour',
    urlImage:
    'assets/images/search01/ingredients/8.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 9,
    name: 'Coffee',
    cate: 'Grain, Nut',
    per: '1 tablespoon of coffee flour',
    urlImage:
    'assets/images/search01/ingredients/9.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 10,
    name: 'Broccoli',
    cate: 'Veg',
    per: '1 cup (91g)',
    urlImage:
    'assets/images/search01/ingredients/10.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: ' 1.6g',
    fiber: '1.5g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Improves Diabetes Management','Promotes Regularity','Aids Weight Loss', 'Lowers Blood Pressure', 'Lowers Blood Pressure'],
  ),
  Ingredient(
    id: 11,
    name: 'Radish',
    cate: 'Veg',
    per: '1 cup (92g)',
    urlImage:
    'assets/images/search01/ingredients/11.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 12,
    name: 'Cabbage',
    cate: 'Veg',
    per: '1 cup (72g)',
    urlImage:
    'assets/images/search01/ingredients/12.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 13,
    name: 'Mushroom',
    cate: 'Veg',
    per: '1 cup (72g)',
    urlImage:
    'assets/images/search01/ingredients/13.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 14,
    name: 'Lettuce',
    cate: 'Veg',
    per: '1 cup (70g)',
    urlImage:
    'assets/images/search01/ingredients/14.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 15,
    name: 'Cucumber',
    cate: 'Veg',
    per: '1 cup (92g)',
    urlImage:
    'assets/images/search01/ingredients/15.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 16,
    name: 'Onion',
    cate: 'Veg',
    per: '1 cup (89g)',
    urlImage:
    'assets/images/search01/ingredients/16.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 17,
    name: 'Carrot',
    cate: 'Veg',
    per: '1 cup (92g)',
    urlImage:
    'assets/images/search01/ingredients/17.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 18,
    name: 'Corn',
    cate: 'Pasta',
    per: '1 medium (6 3/4" to 7 1/2" long)',
    urlImage:
    'assets/images/search01/ingredients/18.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 19,
    name: 'Potato',
    cate: 'Veg',
    per: '1 medium potato (130 grams)',
    urlImage:
    'assets/images/search01/ingredients/19.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 20,
    name: 'Tomato',
    cate: 'Veg',
    per: '1 small (91g)',
    urlImage:
    'assets/images/search01/ingredients/20.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 21,
    name: 'Bell pepper',
    cate: 'Veg',
    per: '1 cup (92g)',
    urlImage:
    'assets/images/search01/ingredients/21.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 22,
    name: 'Pumpkin',
    cate: 'Veg',
    per: '1 cup (245g)',
    urlImage:
    'assets/images/search01/ingredients/22.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 23,
    name: 'Rice',
    cate: 'Pasta',
    per: '1 cup (92g)',
    urlImage:
    'assets/images/search01/ingredients/23.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 24,
    name: 'Cheese',
    cate: 'Others',
    per: '1 slice (22g)',
    urlImage:
    'assets/images/search01/ingredients/24.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 25,
    name: 'Eggs',
    cate: 'Egg, Milk',
    per: '1 egg (50g)',
    urlImage:
    'assets/images/search01/ingredients/25.jpg',
    calo: '17',
    fat: '0.2g',
    sodium: '1mg',
    carbo: '5.4g',
    fiber: '1.6g',
    sugar: '1.5g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 26,
    name: 'Chicken',
    cate: 'Meat, Fish',
    per: '1 part (114g)',
    urlImage:
    'assets/images/search01/ingredients/26.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 27,
    name: 'Beef',
    cate: 'Meat, Fish',
    per: '3 ounces (85g) ',
    urlImage:
    'assets/images/search01/ingredients/27.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 28,
    name: 'Pork',
    cate: 'Meat, Fish',
    per: '3-ounce (85g)',
    urlImage:
    'assets/images/search01/ingredients/28.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
  Ingredient(
    id: 29,
    name: 'Fish',
    cate: 'Meat, Fish',
    per: 'half fillet (154g)',
    urlImage:
    'assets/images/search01/ingredients/29.jpg',
    calo: '62',
    fat: '0.3g',
    sodium: '2mg',
    carbo: '16g',
    fiber: '1g',
    sugar: '15g',
    protein: '0.6g',
    healthBenifit: ['Prevents Deficiency','Improved Heart Health','Slower Age-Related Decline', 'Improved Eye Health','Better Immune Function'],
  ),
  Ingredient(
    id: 30,
    name: 'Shrimp',
    cate: 'Meat, Fish',
    per: '3 oz (84g)',
    urlImage:
    'assets/images/search01/ingredients/30.jpg',
    calo: '49',
    fat: '0.5g',
    sodium: '1.5mg',
    carbo: ' 11.7g',
    fiber: '3g',
    sugar: '7.4g',
    protein: '1g',
    healthBenifit: ['Prevents High Blood Sugar','Eases Arthritis Symptoms','Promotes Wound Healing', 'Promotes Heart Health', 'May Reduce Risk of Colon Cancer'],
  ),
];